// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calculator/calculatorpb/calculator.proto

package calculatorpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Calculating struct {
	NumbOne              int32    `protobuf:"varint,1,opt,name=numbOne,proto3" json:"numbOne,omitempty"`
	NumbTwo              int32    `protobuf:"varint,2,opt,name=numbTwo,proto3" json:"numbTwo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Calculating) Reset()         { *m = Calculating{} }
func (m *Calculating) String() string { return proto.CompactTextString(m) }
func (*Calculating) ProtoMessage()    {}
func (*Calculating) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{0}
}

func (m *Calculating) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Calculating.Unmarshal(m, b)
}
func (m *Calculating) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Calculating.Marshal(b, m, deterministic)
}
func (m *Calculating) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Calculating.Merge(m, src)
}
func (m *Calculating) XXX_Size() int {
	return xxx_messageInfo_Calculating.Size(m)
}
func (m *Calculating) XXX_DiscardUnknown() {
	xxx_messageInfo_Calculating.DiscardUnknown(m)
}

var xxx_messageInfo_Calculating proto.InternalMessageInfo

func (m *Calculating) GetNumbOne() int32 {
	if m != nil {
		return m.NumbOne
	}
	return 0
}

func (m *Calculating) GetNumbTwo() int32 {
	if m != nil {
		return m.NumbTwo
	}
	return 0
}

type CalculatorRequest struct {
	Calculating          *Calculating `protobuf:"bytes,1,opt,name=calculating,proto3" json:"calculating,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CalculatorRequest) Reset()         { *m = CalculatorRequest{} }
func (m *CalculatorRequest) String() string { return proto.CompactTextString(m) }
func (*CalculatorRequest) ProtoMessage()    {}
func (*CalculatorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{1}
}

func (m *CalculatorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculatorRequest.Unmarshal(m, b)
}
func (m *CalculatorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculatorRequest.Marshal(b, m, deterministic)
}
func (m *CalculatorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculatorRequest.Merge(m, src)
}
func (m *CalculatorRequest) XXX_Size() int {
	return xxx_messageInfo_CalculatorRequest.Size(m)
}
func (m *CalculatorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculatorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CalculatorRequest proto.InternalMessageInfo

func (m *CalculatorRequest) GetCalculating() *Calculating {
	if m != nil {
		return m.Calculating
	}
	return nil
}

type CalculatorResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculatorResponse) Reset()         { *m = CalculatorResponse{} }
func (m *CalculatorResponse) String() string { return proto.CompactTextString(m) }
func (*CalculatorResponse) ProtoMessage()    {}
func (*CalculatorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{2}
}

func (m *CalculatorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculatorResponse.Unmarshal(m, b)
}
func (m *CalculatorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculatorResponse.Marshal(b, m, deterministic)
}
func (m *CalculatorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculatorResponse.Merge(m, src)
}
func (m *CalculatorResponse) XXX_Size() int {
	return xxx_messageInfo_CalculatorResponse.Size(m)
}
func (m *CalculatorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculatorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CalculatorResponse proto.InternalMessageInfo

func (m *CalculatorResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type PrimeNumber struct {
	Prime                int32    `protobuf:"varint,1,opt,name=prime,proto3" json:"prime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeNumber) Reset()         { *m = PrimeNumber{} }
func (m *PrimeNumber) String() string { return proto.CompactTextString(m) }
func (*PrimeNumber) ProtoMessage()    {}
func (*PrimeNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{3}
}

func (m *PrimeNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeNumber.Unmarshal(m, b)
}
func (m *PrimeNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeNumber.Marshal(b, m, deterministic)
}
func (m *PrimeNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeNumber.Merge(m, src)
}
func (m *PrimeNumber) XXX_Size() int {
	return xxx_messageInfo_PrimeNumber.Size(m)
}
func (m *PrimeNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeNumber.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeNumber proto.InternalMessageInfo

func (m *PrimeNumber) GetPrime() int32 {
	if m != nil {
		return m.Prime
	}
	return 0
}

type PrimeNumberDecompRequest struct {
	PrimeNumber          *PrimeNumber `protobuf:"bytes,1,opt,name=primeNumber,proto3" json:"primeNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PrimeNumberDecompRequest) Reset()         { *m = PrimeNumberDecompRequest{} }
func (m *PrimeNumberDecompRequest) String() string { return proto.CompactTextString(m) }
func (*PrimeNumberDecompRequest) ProtoMessage()    {}
func (*PrimeNumberDecompRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{4}
}

func (m *PrimeNumberDecompRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeNumberDecompRequest.Unmarshal(m, b)
}
func (m *PrimeNumberDecompRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeNumberDecompRequest.Marshal(b, m, deterministic)
}
func (m *PrimeNumberDecompRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeNumberDecompRequest.Merge(m, src)
}
func (m *PrimeNumberDecompRequest) XXX_Size() int {
	return xxx_messageInfo_PrimeNumberDecompRequest.Size(m)
}
func (m *PrimeNumberDecompRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeNumberDecompRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeNumberDecompRequest proto.InternalMessageInfo

func (m *PrimeNumberDecompRequest) GetPrimeNumber() *PrimeNumber {
	if m != nil {
		return m.PrimeNumber
	}
	return nil
}

type PrimeNumberDecompResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeNumberDecompResponse) Reset()         { *m = PrimeNumberDecompResponse{} }
func (m *PrimeNumberDecompResponse) String() string { return proto.CompactTextString(m) }
func (*PrimeNumberDecompResponse) ProtoMessage()    {}
func (*PrimeNumberDecompResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{5}
}

func (m *PrimeNumberDecompResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeNumberDecompResponse.Unmarshal(m, b)
}
func (m *PrimeNumberDecompResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeNumberDecompResponse.Marshal(b, m, deterministic)
}
func (m *PrimeNumberDecompResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeNumberDecompResponse.Merge(m, src)
}
func (m *PrimeNumberDecompResponse) XXX_Size() int {
	return xxx_messageInfo_PrimeNumberDecompResponse.Size(m)
}
func (m *PrimeNumberDecompResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeNumberDecompResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeNumberDecompResponse proto.InternalMessageInfo

func (m *PrimeNumberDecompResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type ComputeAverageRequest struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComputeAverageRequest) Reset()         { *m = ComputeAverageRequest{} }
func (m *ComputeAverageRequest) String() string { return proto.CompactTextString(m) }
func (*ComputeAverageRequest) ProtoMessage()    {}
func (*ComputeAverageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{6}
}

func (m *ComputeAverageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComputeAverageRequest.Unmarshal(m, b)
}
func (m *ComputeAverageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComputeAverageRequest.Marshal(b, m, deterministic)
}
func (m *ComputeAverageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComputeAverageRequest.Merge(m, src)
}
func (m *ComputeAverageRequest) XXX_Size() int {
	return xxx_messageInfo_ComputeAverageRequest.Size(m)
}
func (m *ComputeAverageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ComputeAverageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ComputeAverageRequest proto.InternalMessageInfo

func (m *ComputeAverageRequest) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type ComputeAverageResponse struct {
	Result               float32  `protobuf:"fixed32,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComputeAverageResponse) Reset()         { *m = ComputeAverageResponse{} }
func (m *ComputeAverageResponse) String() string { return proto.CompactTextString(m) }
func (*ComputeAverageResponse) ProtoMessage()    {}
func (*ComputeAverageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{7}
}

func (m *ComputeAverageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComputeAverageResponse.Unmarshal(m, b)
}
func (m *ComputeAverageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComputeAverageResponse.Marshal(b, m, deterministic)
}
func (m *ComputeAverageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComputeAverageResponse.Merge(m, src)
}
func (m *ComputeAverageResponse) XXX_Size() int {
	return xxx_messageInfo_ComputeAverageResponse.Size(m)
}
func (m *ComputeAverageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ComputeAverageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ComputeAverageResponse proto.InternalMessageInfo

func (m *ComputeAverageResponse) GetResult() float32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type FindMaximumRequest struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindMaximumRequest) Reset()         { *m = FindMaximumRequest{} }
func (m *FindMaximumRequest) String() string { return proto.CompactTextString(m) }
func (*FindMaximumRequest) ProtoMessage()    {}
func (*FindMaximumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{8}
}

func (m *FindMaximumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindMaximumRequest.Unmarshal(m, b)
}
func (m *FindMaximumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindMaximumRequest.Marshal(b, m, deterministic)
}
func (m *FindMaximumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindMaximumRequest.Merge(m, src)
}
func (m *FindMaximumRequest) XXX_Size() int {
	return xxx_messageInfo_FindMaximumRequest.Size(m)
}
func (m *FindMaximumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindMaximumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindMaximumRequest proto.InternalMessageInfo

func (m *FindMaximumRequest) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type FindMaximumResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindMaximumResponse) Reset()         { *m = FindMaximumResponse{} }
func (m *FindMaximumResponse) String() string { return proto.CompactTextString(m) }
func (*FindMaximumResponse) ProtoMessage()    {}
func (*FindMaximumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{9}
}

func (m *FindMaximumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindMaximumResponse.Unmarshal(m, b)
}
func (m *FindMaximumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindMaximumResponse.Marshal(b, m, deterministic)
}
func (m *FindMaximumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindMaximumResponse.Merge(m, src)
}
func (m *FindMaximumResponse) XXX_Size() int {
	return xxx_messageInfo_FindMaximumResponse.Size(m)
}
func (m *FindMaximumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindMaximumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindMaximumResponse proto.InternalMessageInfo

func (m *FindMaximumResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*Calculating)(nil), "calculator.Calculating")
	proto.RegisterType((*CalculatorRequest)(nil), "calculator.CalculatorRequest")
	proto.RegisterType((*CalculatorResponse)(nil), "calculator.CalculatorResponse")
	proto.RegisterType((*PrimeNumber)(nil), "calculator.PrimeNumber")
	proto.RegisterType((*PrimeNumberDecompRequest)(nil), "calculator.PrimeNumberDecompRequest")
	proto.RegisterType((*PrimeNumberDecompResponse)(nil), "calculator.PrimeNumberDecompResponse")
	proto.RegisterType((*ComputeAverageRequest)(nil), "calculator.ComputeAverageRequest")
	proto.RegisterType((*ComputeAverageResponse)(nil), "calculator.ComputeAverageResponse")
	proto.RegisterType((*FindMaximumRequest)(nil), "calculator.FindMaximumRequest")
	proto.RegisterType((*FindMaximumResponse)(nil), "calculator.FindMaximumResponse")
}

func init() {
	proto.RegisterFile("calculator/calculatorpb/calculator.proto", fileDescriptor_7f42938f8c8365cf)
}

var fileDescriptor_7f42938f8c8365cf = []byte{
	// 373 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xcf, 0x4f, 0xf2, 0x40,
	0x14, 0xfc, 0x4a, 0x02, 0x5f, 0xbe, 0xd7, 0x2f, 0x24, 0x3c, 0x15, 0x6b, 0x13, 0x7f, 0xad, 0x9a,
	0x70, 0x40, 0x20, 0x70, 0xf2, 0x88, 0x18, 0x4f, 0x8a, 0xa6, 0xe2, 0x45, 0x4f, 0x6d, 0x79, 0x21,
	0x4d, 0x68, 0xb7, 0xb6, 0x5d, 0xf0, 0x6f, 0xf7, 0x64, 0x84, 0x96, 0xdd, 0x4a, 0x81, 0x1b, 0xb3,
	0x6f, 0x76, 0x66, 0x78, 0xd3, 0x85, 0x86, 0x6b, 0x4f, 0x5d, 0x31, 0xb5, 0x13, 0x1e, 0xb5, 0xe5,
	0xcf, 0xd0, 0x51, 0x40, 0x2b, 0x8c, 0x78, 0xc2, 0x11, 0xe4, 0x09, 0xeb, 0x83, 0x3e, 0x48, 0x91,
	0x17, 0x4c, 0xd0, 0x80, 0xbf, 0x81, 0xf0, 0x9d, 0xa7, 0x80, 0x0c, 0xed, 0x4c, 0x6b, 0x94, 0xad,
	0x0c, 0x66, 0x93, 0xd1, 0x9c, 0x1b, 0x25, 0x39, 0x19, 0xcd, 0x39, 0x1b, 0x42, 0x6d, 0xb0, 0x12,
	0xb4, 0xe8, 0x43, 0x50, 0x9c, 0xe0, 0x0d, 0xe8, 0xae, 0xd4, 0x5d, 0x88, 0xe9, 0xdd, 0xc3, 0x96,
	0x92, 0x45, 0xb1, 0xb5, 0x54, 0x2e, 0x6b, 0x02, 0xaa, 0x7a, 0x71, 0xc8, 0x83, 0x98, 0xb0, 0x0e,
	0x95, 0x88, 0x62, 0x31, 0x4d, 0xd2, 0x60, 0x29, 0x62, 0x17, 0xa0, 0x3f, 0x47, 0x9e, 0x4f, 0x43,
	0xe1, 0x3b, 0x14, 0xe1, 0x3e, 0x94, 0xc3, 0x1f, 0x98, 0xb2, 0x96, 0x80, 0xbd, 0x82, 0xa1, 0x90,
	0xee, 0xc8, 0xe5, 0x7e, 0xa8, 0x24, 0x0d, 0xe5, 0xac, 0x28, 0xa9, 0x72, 0xd5, 0x52, 0xb9, 0xac,
	0x07, 0x47, 0x05, 0xb2, 0x3b, 0x02, 0xb7, 0xe1, 0x60, 0xc0, 0xfd, 0x50, 0x24, 0xd4, 0x9f, 0x51,
	0x64, 0x4f, 0x28, 0x0b, 0x52, 0x87, 0x4a, 0x20, 0x33, 0x94, 0xad, 0x14, 0xb1, 0x0e, 0xd4, 0x7f,
	0x5f, 0x28, 0xb4, 0x28, 0xad, 0x2c, 0x9a, 0x80, 0xf7, 0x5e, 0x30, 0x7e, 0xb4, 0x3f, 0x3d, 0x5f,
	0xf8, 0xbb, 0xf4, 0xaf, 0x61, 0x2f, 0xc7, 0xde, 0x9e, 0xbf, 0xfb, 0x55, 0x52, 0xfb, 0x7e, 0xa1,
	0x68, 0xe6, 0xb9, 0x84, 0x0f, 0xf0, 0x2f, 0x3b, 0x24, 0x3c, 0x2e, 0xea, 0x79, 0xf5, 0x6d, 0x98,
	0x27, 0x9b, 0xc6, 0x4b, 0x67, 0xf6, 0x07, 0xc7, 0x50, 0x5b, 0x5b, 0x2c, 0x5e, 0x6e, 0xe8, 0x24,
	0x57, 0xa7, 0x79, 0xb5, 0x83, 0x95, 0x79, 0x74, 0x34, 0x7c, 0x87, 0x6a, 0x7e, 0xb1, 0x78, 0x9e,
	0x4b, 0x56, 0xd4, 0x92, 0xc9, 0xb6, 0x51, 0x32, 0xf1, 0x86, 0x86, 0x23, 0xd0, 0x95, 0xad, 0x62,
	0xee, 0x3f, 0xaf, 0x97, 0x63, 0x9e, 0x6e, 0x9c, 0x4b, 0xcd, 0x8e, 0x76, 0x5b, 0x7d, 0xfb, 0xaf,
	0xbe, 0x6d, 0xa7, 0xb2, 0x78, 0xd1, 0xbd, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf6, 0x6f, 0x98,
	0x0e, 0xfd, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CalculatorServiceClient is the client API for CalculatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalculatorServiceClient interface {
	Calculate(ctx context.Context, in *CalculatorRequest, opts ...grpc.CallOption) (*CalculatorResponse, error)
	PrimeNumberDecomp(ctx context.Context, in *PrimeNumberDecompRequest, opts ...grpc.CallOption) (CalculatorService_PrimeNumberDecompClient, error)
	ComputeAverage(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_ComputeAverageClient, error)
	FindMaximum(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_FindMaximumClient, error)
}

type calculatorServiceClient struct {
	cc *grpc.ClientConn
}

func NewCalculatorServiceClient(cc *grpc.ClientConn) CalculatorServiceClient {
	return &calculatorServiceClient{cc}
}

func (c *calculatorServiceClient) Calculate(ctx context.Context, in *CalculatorRequest, opts ...grpc.CallOption) (*CalculatorResponse, error) {
	out := new(CalculatorResponse)
	err := c.cc.Invoke(ctx, "/calculator.CalculatorService/Calculate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorServiceClient) PrimeNumberDecomp(ctx context.Context, in *PrimeNumberDecompRequest, opts ...grpc.CallOption) (CalculatorService_PrimeNumberDecompClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CalculatorService_serviceDesc.Streams[0], "/calculator.CalculatorService/PrimeNumberDecomp", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServicePrimeNumberDecompClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CalculatorService_PrimeNumberDecompClient interface {
	Recv() (*PrimeNumberDecompResponse, error)
	grpc.ClientStream
}

type calculatorServicePrimeNumberDecompClient struct {
	grpc.ClientStream
}

func (x *calculatorServicePrimeNumberDecompClient) Recv() (*PrimeNumberDecompResponse, error) {
	m := new(PrimeNumberDecompResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculatorServiceClient) ComputeAverage(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_ComputeAverageClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CalculatorService_serviceDesc.Streams[1], "/calculator.CalculatorService/ComputeAverage", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServiceComputeAverageClient{stream}
	return x, nil
}

type CalculatorService_ComputeAverageClient interface {
	Send(*ComputeAverageRequest) error
	CloseAndRecv() (*ComputeAverageResponse, error)
	grpc.ClientStream
}

type calculatorServiceComputeAverageClient struct {
	grpc.ClientStream
}

func (x *calculatorServiceComputeAverageClient) Send(m *ComputeAverageRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calculatorServiceComputeAverageClient) CloseAndRecv() (*ComputeAverageResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ComputeAverageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculatorServiceClient) FindMaximum(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_FindMaximumClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CalculatorService_serviceDesc.Streams[2], "/calculator.CalculatorService/FindMaximum", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServiceFindMaximumClient{stream}
	return x, nil
}

type CalculatorService_FindMaximumClient interface {
	Send(*FindMaximumRequest) error
	Recv() (*FindMaximumResponse, error)
	grpc.ClientStream
}

type calculatorServiceFindMaximumClient struct {
	grpc.ClientStream
}

func (x *calculatorServiceFindMaximumClient) Send(m *FindMaximumRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calculatorServiceFindMaximumClient) Recv() (*FindMaximumResponse, error) {
	m := new(FindMaximumResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CalculatorServiceServer is the server API for CalculatorService service.
type CalculatorServiceServer interface {
	Calculate(context.Context, *CalculatorRequest) (*CalculatorResponse, error)
	PrimeNumberDecomp(*PrimeNumberDecompRequest, CalculatorService_PrimeNumberDecompServer) error
	ComputeAverage(CalculatorService_ComputeAverageServer) error
	FindMaximum(CalculatorService_FindMaximumServer) error
}

// UnimplementedCalculatorServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCalculatorServiceServer struct {
}

func (*UnimplementedCalculatorServiceServer) Calculate(ctx context.Context, req *CalculatorRequest) (*CalculatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Calculate not implemented")
}
func (*UnimplementedCalculatorServiceServer) PrimeNumberDecomp(req *PrimeNumberDecompRequest, srv CalculatorService_PrimeNumberDecompServer) error {
	return status.Errorf(codes.Unimplemented, "method PrimeNumberDecomp not implemented")
}
func (*UnimplementedCalculatorServiceServer) ComputeAverage(srv CalculatorService_ComputeAverageServer) error {
	return status.Errorf(codes.Unimplemented, "method ComputeAverage not implemented")
}
func (*UnimplementedCalculatorServiceServer) FindMaximum(srv CalculatorService_FindMaximumServer) error {
	return status.Errorf(codes.Unimplemented, "method FindMaximum not implemented")
}

func RegisterCalculatorServiceServer(s *grpc.Server, srv CalculatorServiceServer) {
	s.RegisterService(&_CalculatorService_serviceDesc, srv)
}

func _CalculatorService_Calculate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServiceServer).Calculate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.CalculatorService/Calculate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServiceServer).Calculate(ctx, req.(*CalculatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalculatorService_PrimeNumberDecomp_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimeNumberDecompRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalculatorServiceServer).PrimeNumberDecomp(m, &calculatorServicePrimeNumberDecompServer{stream})
}

type CalculatorService_PrimeNumberDecompServer interface {
	Send(*PrimeNumberDecompResponse) error
	grpc.ServerStream
}

type calculatorServicePrimeNumberDecompServer struct {
	grpc.ServerStream
}

func (x *calculatorServicePrimeNumberDecompServer) Send(m *PrimeNumberDecompResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _CalculatorService_ComputeAverage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculatorServiceServer).ComputeAverage(&calculatorServiceComputeAverageServer{stream})
}

type CalculatorService_ComputeAverageServer interface {
	SendAndClose(*ComputeAverageResponse) error
	Recv() (*ComputeAverageRequest, error)
	grpc.ServerStream
}

type calculatorServiceComputeAverageServer struct {
	grpc.ServerStream
}

func (x *calculatorServiceComputeAverageServer) SendAndClose(m *ComputeAverageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calculatorServiceComputeAverageServer) Recv() (*ComputeAverageRequest, error) {
	m := new(ComputeAverageRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _CalculatorService_FindMaximum_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculatorServiceServer).FindMaximum(&calculatorServiceFindMaximumServer{stream})
}

type CalculatorService_FindMaximumServer interface {
	Send(*FindMaximumResponse) error
	Recv() (*FindMaximumRequest, error)
	grpc.ServerStream
}

type calculatorServiceFindMaximumServer struct {
	grpc.ServerStream
}

func (x *calculatorServiceFindMaximumServer) Send(m *FindMaximumResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calculatorServiceFindMaximumServer) Recv() (*FindMaximumRequest, error) {
	m := new(FindMaximumRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _CalculatorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.CalculatorService",
	HandlerType: (*CalculatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Calculate",
			Handler:    _CalculatorService_Calculate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PrimeNumberDecomp",
			Handler:       _CalculatorService_PrimeNumberDecomp_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ComputeAverage",
			Handler:       _CalculatorService_ComputeAverage_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "FindMaximum",
			Handler:       _CalculatorService_FindMaximum_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "calculator/calculatorpb/calculator.proto",
}
